version: '3'
services:
  oxotly_bot:
    build:
      context: .
      dockerfile: ./Dockerfile

  redis: 
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: "redis-server /redis.conf"
